### ISSUE TITLE
Change it with the function below

### ISSUE THREAD

**Issue by Sorooshi** [Sorooshi/DSDs#3]
https://github.com/Sorooshi/DSDs/blob/4cfaccd2ea1a202e98c7545950709a73c2b07d0a/DSD/package/data/data_loader.py#L135

def get_spectrogram(waveformm, frame_length, frame_step):
  % Convert the waveform to a spectrogram via a STFT.
  spectrogram = tf.signal.stft(
      waveform, frame_length= frame_length, frame_step= frame_step)
  % Obtain the magnitude of the STFT.
  spectrogram = tf.abs(spectrogram)
  % Add a `channels` dimension so that the spectrogram can be used
  % as image-like input data with convolution layers (which expect
  % shape (`batch_size`, `height`, `width`, `channels`).
  spectrogram = spectrogram[..., tf.newaxis]
  return spectrogram

Also please, check the obtained results with the following function:

import tensorflow_io as tfio

spectrogram = tfio.audio.spectrogram(
    fade, nfft=512, window=512, stride=256)
They must identical using the same params.

**Comment by anyakazachkova** [comment]
updated spectograms according to this functions
