### ISSUE TITLE
Change the splitting framework to indices

### ISSUE THREAD

**Issue by Sorooshi** [Sorooshi/DSDs#4]
https://github.com/Sorooshi/DSDs/blob/4cfaccd2ea1a202e98c7545950709a73c2b07d0a/DSD/package/data/data_loader.py#L191

What I did for hand-crafted features (previously), was fine, but with spectrograms, you will definitely face memory issues. Please, only split the indices and do not keep the whole, approximately 5 GB files in the RAM. You won't be able to train the model. You should load the data per batch.

**Comment by anyakazachkova** [comment]
updated it id data_loader.py

**Comment by Sorooshi** [comment]
Yes, everything seems correct, thank you!
